Create GH Pages
morganstanley/message-broker pull request #31
Opened 2024-03-18 15:03 UTC by aidanm3341

This PR is to add in the initial GH Pages for the Message Broker

2024-03-26 14:52 UTC, mimiflynn requested changes
Looking better! I should have been more specific: the `/site` directory will live with the codebase for `message-broker` and an Action will build it to the `gh-pages` branch upon merge to `main`. There is no need to delete files in this PR.

As I mentioned in a comment below (before I understood what you were getting at), let's point this PR to `main` and bring back all of the `message-broker` files.

Refer to the [ComposeUI project for reference](https://github.com/morganstanley/ComposeUI) where this [PR added the Pages](https://github.com/morganstanley/ComposeUI/pull/522/files).

2024-03-26 14:52 UTC, mimiflynn commented on .github/workflows/deploy.yml
The names of these files are confusing. Lets add a prefix of `site-` to the GH pages site workflow `.yml` files (`deploy` and `pr-build`). I will change this on my end as well.

2024-03-26 14:52 UTC, mimiflynn commented on .github/workflows/deploy.yml
> +      - main
This action will only run when the PR is merged into the `main` branch. Please adjust this PR to merge to the `main` branch.

2024-03-26 14:52 UTC, mimiflynn commented on .github/workflows/deploy.yml
> +          target_branch: gh-pages
This action builds the site and pushes it to a `gh-pages` branch which will then be picked up by the settings to publish the site which is why I added the comment above asking to adjust the target branch of this PR.

[Here are some relevant docs](https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages#about-custom-workflows), although we aren't using Jekyll.

2024-03-26 14:52 UTC, mimiflynn commented on .github/dependabot.yml
Since the main project, `message-broker` is an `npm` project as well as the `/site` directory, we can merge these differences to cover both. Instead of removing what was already there, include the `package-ecosystem` contents of from the `ms-gh-pages` project (lines 8-15 in the updated file below) to the end of the file. This way, dependabot will (probably) check the `/` weekly, while checking `/site` monthly and will group the `gatsby` changes into a single PR.

For lines 17-24, go ahead and continue to allow that to replace the `package-ecosystem: "github-actions"` section so it only checks monthly and will group the changes into a single PR.

Happy to chat about this over a call.

2024-04-12 12:09 UTC, aidanm3341 commented
given some of my misunderstandings in this PR, I'm going to close this one and create a fresh one which has the site in the correct structure

2024-04-12 12:09 UTC, closed without merging