created github pages directory
morganstanley/message-broker pull request #38
Opened 2024-04-12 13:33 UTC by aidanm3341

added a site directory with documentation of the Message Broker.

also create the relevant GitHub Actions to deploy it and keep it up to date with dependabot

2024-04-19 14:02 UTC, mimiflynn commented
It looks like the site build is failing due to a missing `/site/package-lock.json`. If you run the build locally and commit the resulting `package-lock.json` it should resolve this issue.

2024-04-23 13:59 UTC, mimiflynn requested changes
Looks good! Almost there!

2024-04-23 13:59 UTC, mimiflynn commented on site/gatsby-config.js
> +    siteUrl: 'http://opensource.morganstanley.com',
```suggestion
    siteUrl: 'http://opensource.morganstanley.com/message-broker',
```

2024-04-23 13:59 UTC, mimiflynn commented on site/gatsby-config.js
> +  pathPrefix: `/`, // include subdirectory
```suggestion
  pathPrefix: `/message-broker`, // include subdirectory
```

2024-04-23 13:59 UTC, mimiflynn commented on site/gatsby-config.js
> +  siteMetadata: {
Fill our `title` and `description` for this project similar to the [ComposeUI](https://github.com/morganstanley/ComposeUI/blob/b3a21e454f785a8e4825f6f39e810876c1c002c2/site/gatsby-config.js) config.

2024-04-23 13:59 UTC, mimiflynn commented on site/content/news/hello-world.mdx
Probably should remove or replace the content of this page.

2024-04-24 14:00 UTC, aidanm3341 commented on site/content/news/hello-world.mdx
When I removed this, I got multiple of the following error: 'Cannot query field "date" on type "MdxFrontmatter".' when I try and run the site. I managed to fix it just by adding a dummy date to one of the other files, but it looks like the graphql queries requires that there is a date defined _somewhere_ in the site which is a little awkward.

2024-04-24 14:56 UTC, mimiflynn commented on site/content/alternatives.mdx
> +date: 2024-04-24
I see, let me dig into why this is requiring a date. We can leave it like this for now. Thanks!

2024-04-26 09:25 UTC, merged